### ISSUE TITLE
[Feature Request] arbitrary data signing 

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-money/terra-web-extensions#2]
Can we make new interface for signing the arbitrary data like metamask 

https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask

I’m not sure this already available, can we get the pubkey of address?? If not, it also good to have that feature too.

**Comment by tk-o** [comment]
Hey @iamssen, would you be able to share a high-level estimate on when do you expect this update to be released?

Related PR: https://github.com/terra-money/wallet-provider/issues/21

**Comment by iamssen** [comment]
@tk-o Ah. this feature already released on current extension and this extension both

**Comment by tk-o** [comment]
Thanks 🤝  I was able to implement the flow I wanted. I have a question around improving user experience.

How much effort would it be to add a preview of the data being signed? Right now, the extension says:
> The origin is signing an arbitrary data.

![image](https://user-images.githubusercontent.com/3687215/144693892-34760438-0aa8-4056-acdc-9e62c6bc47dc.png)

---

Improved UX would require sharing with the user what data they are about to sign, so we could improve users' trust to the extension. At the end of the day, a user needs to know what they sign with their private key.

An example UI from Metamask. It shows exactly the arbitrary data attached to the Signature Request:
![image](https://user-images.githubusercontent.com/3687215/144693979-e1192cf5-ca72-479e-8821-0c7e3c28e692.png)

IMO, it should be a default mode to present the message that the user is signing. Otherwise, the users' might not want to sign anything due to the lack of transparency.

What do you think, @iamssen?

**Comment by Ruborcalor** [comment]
Echoing @tk-o, I think this would make user's much more comfortable signing bytes if they know what they are signing.

Also, because these signed bytes don't include a fee they can never be run on the blockchain and can never be used to change the state of the blockchain, correct? This information could also help make users more comfortable signing bytes.

**Comment by tk-o** [comment]
> signed bytes don't include a fee they can never be run on the blockchain and can never be used to change the state of the blockchain, correct?

Indeed, signing bytes it an entirely off-chain action.

It's especially useful when, for instance, a user is accepting particular Terms and Conditions document. The service will need to store the signature so it could (if needed in the future) assert the T&Cs were accepted by a particular user.
